version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: my_sql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "web_basic"
      TZ: "Asia/Seoul"
    volumes:
      - mysql_vol:/var/lib/mysql # 데이터 영속화: mysql_vol → MySQL의 실제 DB 데이터가 여기에 저장됨
      - ./db-init:/docker-entrypoint-initdb.d  # 초기 SQL 실행: ./db-init/init.sql 파일 등을 통해 컨테이너 초기 구동 시 테이블 생성 가능(SQL 스크립트 자동 실행 경로)
      - /etc/localtime:/etc/localtime:ro  # 시간 동기화: 호스트의 시간을 컨테이너와 동일하게 맞춤
    ports:
      - "3306:3306"
    networks:
      - web_net  # tomcat과 같은 네트워크에 연결되어 같은 내부 이름으로 통신할 수 있다 (예: my_sql로 접근)

  tomcat:
    build: . # 현재 디렉토리에 있는 Dockerfile을 기반으로 이미지를 새로 빌드
    container_name: my_tomcat
    ports:
      - "80:8080"
    networks:
      - web_net
    depends_on:    # mysql 컨테이너가 먼저 시작된 후 tomcat이 시작된다.
      - mysql
    volumes:
      - /home/ubuntu/upload:/usr/local/tomcat/webapps/save  # Tomcat 컨테이너의 /webapps/save 경로와 호스트의 /home/ubuntu/upload 경로를 연결
      
volumes:
  mysql_vol:

networks:
  web_net: # Tomcat과 MySQL이 같은 네트워크로 묶여 내부 DNS 이름으로 서로 접근 가능 (my_sql:3306 등)
